---
# This will be reiterated in the chezmoi.yaml, see template
config:
  os: linux_ubuntu # supported: linux_ubuntu, darwin
  wsl: false # set to true if running in WSL
  minimal: false # essential packages only, no github auth
  headless: true # no GUI, e.g. proxmox lxc

  timezone: Asia/Tokyo # choose from /usr/share/zoneinfo
  locale: en_US.UTF-8 # choose from /usr/share/i18n/SUPPORTED
  git_email: me@akhdan.dev
  git_name: Akhdan Fadhilah
  nvim_config: nvim-minimal # adjust manually

# NEVER SHARE PUBLICLY, will be used as environment variables
secrets:
  anthropic_api_key: "a-key" # used in neovim, aider, or any
  openai_api_key: "a-key" # used in neovim, aider, or any
  obsidian_vault: "a-path" # absolute path to Obsidian vault, for neovim obsidian plugin
  overleaf_cookies: "a-cookie" # used in neovim airlatex plugin

packages:
  linux_ubuntu:
    essential:
      - build-essential # compiling software (gcc, g++, etc.)
      - ca-certificates # apt to work with https repos
      - curl # download files and transfer data
      - dnsutils # dns tools (dig, nslookup, etc.)
      - fail2ban # protects against brute force attacks
      - git # version control system
      - openssh-client # ssh client
      - openssh-server # ssh server
      - software-properties-common # apt additional, e.g. add-apt-repository
      - vim # text editor
      - tmux # terminal multiplexer
      - wget # curl alternative
    dev:
      - bat # cat alternative
      - eza # ls alternative
      - fd-find # find alternative
      - fzf # fuzzy finder
      - htop # process monitor
      - jq # json processor
      - ncdu # disk usage analyzer
      - python3-pip # python3 pip
      - python3-venv # python3 venv
      - ripgrep # grep alternative
      - tree # directory tree viewer
      - unzip # extract files from zip archives
      - zip # create zip archives

  darwin: [] # TODO: add brew packages

oh_my_zsh:
  themes:
    - name: powerlevel10k
      repo: https://github.com/romkatv/powerlevel10k.git
  plugins:
    - name: zsh-autosuggestions
      repo: https://github.com/zsh-users/zsh-autosuggestions
    - name: zsh-autocomplete
      repo: https://github.com/marlonrichert/zsh-autocomplete.git
    - name: fast-syntax-highlighting
      repo: https://github.com/zdharma-continuum/fast-syntax-highlighting.git
    - name: zsh-vi-mode
      repo: https://github.com/jeffreytse/zsh-vi-mode
    - name: conda-zsh-completion
      repo: https://github.com/conda-incubator/conda-zsh-completion