---
- name: Install prerequisites for PPA management
  ansible.builtin.package:
    name:
      - software-properties-common
      - ca-certificates
      - gnupg
    state: present
  become: true

- name: Add Neovim stable PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
    update_cache: true
  become: true

- name: Install Neovim and dependencies for plugins
  ansible.builtin.package:
    name:
      - neovim
      - python3-neovim
      - tree-sitter-cli
      - cmake # telescope-fzf-native for telescope.nvim
    state: present
  become: true

- name: Install NVM for Neovim
  ansible.builtin.include_tasks: nvm.yaml

- name: Install npm dependencies for Neovim plugins
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.nvm/nvm.sh
    npm install -g {{ item }}
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
  loop:
    - yarn
    - markdownlint-cli2
    - "@fsouza/prettierd"
  changed_when: false

- name: Install luarocks for Neovim
  ansible.builtin.apt:
    name:
      - build-essential
      - libreadline-dev
      - unzip
      - luarocks
    state: present
  become: true

- name: Set Neovim as default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/nvim
  become: true
