---
- name: Install and configure Zsh for Ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"
  block:
    - name: Install Zsh
      ansible.builtin.package:
        name: zsh
        state: present
      become: true

    - name: Set Zsh as default shell for current user
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      become: true

- name: Install Oh My Zsh
  block:
    - name: Check if Oh My Zsh is already installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
      register: oh_my_zsh_installed

    - name: Download and install Oh My Zsh
      ansible.builtin.shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      when: not oh_my_zsh_installed.stat.exists
      changed_when: not oh_my_zsh_installed.stat.exists

    - name: Download Oh My Zsh themes from repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/{{ item.name }}"
        version: "{{ item.version | default('HEAD') }}"
        clone: true
        update: false
      loop: "{{ oh_my_zsh.themes }}"
      when: oh_my_zsh.themes is defined

    - name: Download Oh My Zsh plugins from repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
        version: "{{ item.version | default('HEAD') }}"
        clone: true
        update: false
      loop: "{{ oh_my_zsh.plugins }}"
      when: oh_my_zsh.plugins is defined
