---
- name: Bootstrapping and dotfiles in STEROID
  hosts: localhost
  gather_facts: true
  vars_files:
    - "../config.yaml"

  tasks:
    - name: Display detected OS information
      ansible.builtin.debug:
        msg: "Detected OS: {{ ansible_facts['distribution'] | default('Unknown') }} {{ ansible_facts['distribution_version'] | default('') }}"

    - name: Run bootstrap tasks for Ubuntu systems
      ansible.builtin.include_tasks: tasks/bootstrap.yaml
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Run git configuration for Ubuntu systems
      ansible.builtin.include_tasks: tasks/git.yaml
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Run zsh configuration
      ansible.builtin.include_tasks: tasks/zsh.yaml
      when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['os_family'] == "Darwin"

    - name: Run bootstrap playbook for Darwin/macOS systems
      ansible.builtin.debug:
        msg: "Darwin/macOS bootstrap not yet implemented"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Unsupported OS warning
      ansible.builtin.fail:
        msg: "This playbook only supports Ubuntu and Darwin/macOS. Detected: {{ ansible_facts['distribution'] | default(ansible_facts['os_family']) }}"
      when:
        - ansible_facts['distribution'] != "Ubuntu"
        - ansible_facts['os_family'] != "Darwin"

  handlers:
    - name: Restart cron
      ansible.builtin.systemd:
        name: cron
        state: restarted
      become: true

    - name: Reconfigure locales
      ansible.builtin.command: dpkg-reconfigure -f noninteractive locales
      become: true
      changed_when: true

    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      become: true

    - name: GitHub authentication required
      ansible.builtin.debug:
        msg:
          - "================================================================"
          - "GitHub Authentication Required"
          - "================================================================"
          - "SSH key has been generated and configured at: ~/.ssh/github_ed25519"
          - "To complete GitHub authentication, run:"
          - "1. `gh auth login -p ssh`, then follow the prompts and select the generated SSH key"
          - "2. Or manually add the public key to GitHub: `cat ~/.ssh/github_ed25519.pub`"
          - "================================================================"
