---
- name: Bootstrapping and dotfiles in STEROID
  hosts: localhost
  gather_facts: true
  vars_files:
    - "../config.yaml"

  tasks:
    - name: Check for supported OS
      ansible.builtin.fail:
        when:
          - ansible_facts['distribution'] != "Ubuntu"
          - ansible_facts['os_family'] != "Darwin"
        msg: "This playbook only supports Ubuntu and Darwin/macOS only. Detected: {{ ansible_facts['distribution'] | default(ansible_facts['os_family']) }}"

    - name: Ubuntu tasks
      when: ansible_facts['distribution'] == "Ubuntu"
      block:
        - name: Bootstrapping (package, system, and hardening)
          ansible.builtin.include_tasks: tasks/ubuntu.yaml
        - name: Git and GitHub configuration
          ansible.builtin.include_tasks: tasks/git.yaml

    - name: Darwin/macOS tasks
      when: ansible_facts['os_family'] == "Darwin"
      ansible.builtin.debug:
        msg: "Darwin/macOS tasks not yet implemented"

    - name: Configure ZSH and Oh My Zsh
      ansible.builtin.include_tasks: tasks/zsh.yaml

  handlers:
    - name: Restart cron
      ansible.builtin.systemd:
        name: cron
        state: restarted
      become: true

    - name: Reconfigure locales
      ansible.builtin.command: dpkg-reconfigure -f noninteractive locales
      become: true
      changed_when: true

    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      become: true

    - name: GitHub authentication required
      ansible.builtin.debug:
        msg:
          - "================================================================"
          - "GitHub Authentication Required"
          - "================================================================"
          - "SSH key has been generated and configured at: ~/.ssh/github_ed25519"
          - "To complete GitHub authentication, run:"
          - "1. `gh auth login -p ssh`, then follow the prompts and select the generated SSH key"
          - "2. Or manually add the public key to GitHub: `cat ~/.ssh/github_ed25519.pub`"
          - "================================================================"
